os: osx

env:
    global:
        - HOMEBREW_NO_AUTO_UPDATE=1

script:
    - bash install_python.sh > python_install_log.txt
    - bash osx_create_wheel.sh master testing deploy

matrix:
  include:
    - osx_image: xcode9.4
    - osx_image: xcode8.3
    - osx_image: xcode7.3


