os: osx

env:
    global:
        - HOMEBREW_NO_AUTO_UPDATE=1

before_install:
    - brew update
    - brew unlink python

script:
    - bash osx_create_wheel.sh bh_py_api testing deploy

matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8.3
    - osx_image: xcode9.4

